---
  - name: Check if Python is already installed
    command: python3 --version
    register: python_installed
    ignore_errors: yes

  - name: Check if Nginx is already installed
    command: nginx -v
    register: nginx_installed
    ignore_errors: yes

  - name: Install Python and pip
    apt:
      name:
        - python3
        - python3-pip
      state: present
      update_cache: yes
    when: python_installed.rc != 0

  - name: Install Nginx
    apt:
      name: nginx
      state: present
    when: nginx_installed.rc != 0

  - name: Ensure Nginx is running
    service:
      name: nginx
      state: started
      enabled: yes
