---
- name: Deploy PostgreSQL container
  hosts: db
  become: yes

  tasks:
    - name: Stop any local PostgreSQL service
      systemd:
        name: postgresql
        state: stopped
      ignore_errors: yes

    - name: Remove existing PostgreSQL container
      community.docker.docker_container:
        name: postgresdb
        state: absent
      ignore_errors: yes

    - name: Pull PostgreSQL image
      community.docker.docker_image:
        name: postgres:15-alpine
        source: pull

    - name: Run PostgreSQL container
      community.docker.docker_container:
        name: postgresdb
        image: postgres:15-alpine
        state: started
        restart_policy: always
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
