---
- name: Install Docker on all EC2 instances
  hosts: all   # all the instances
  become: yes  # execute like root
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    #new add:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0 #new add

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group (avoid sudo)
      user:
        name: ubuntu
        groups: docker
        append: yes